// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNMoovoG8BLVoelF85UShzJqSdDKvkCJE',
    appId: '1:320837213638:web:d226afad72d8e13b7266c7',
    messagingSenderId: '320837213638',
    projectId: 'expensetracker-999c9',
    authDomain: 'expensetracker-999c9.firebaseapp.com',
    storageBucket: 'expensetracker-999c9.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjnzNnREoQY9tGlq-cM_kTuCbotceMS_I',
    appId: '1:320837213638:android:ffb98394114825ce7266c7',
    messagingSenderId: '320837213638',
    projectId: 'expensetracker-999c9',
    storageBucket: 'expensetracker-999c9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjCBlsNgd5m9k8QCw4YEG1uk0HcNaoN8A',
    appId: '1:320837213638:ios:962ec21c2c273ad47266c7',
    messagingSenderId: '320837213638',
    projectId: 'expensetracker-999c9',
    storageBucket: 'expensetracker-999c9.firebasestorage.app',
    iosBundleId: 'com.example.expenseTracker30',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjCBlsNgd5m9k8QCw4YEG1uk0HcNaoN8A',
    appId: '1:320837213638:ios:962ec21c2c273ad47266c7',
    messagingSenderId: '320837213638',
    projectId: 'expensetracker-999c9',
    storageBucket: 'expensetracker-999c9.firebasestorage.app',
    iosBundleId: 'com.example.expenseTracker30',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBNMoovoG8BLVoelF85UShzJqSdDKvkCJE',
    appId: '1:320837213638:web:35cd3d59df5fae7a7266c7',
    messagingSenderId: '320837213638',
    projectId: 'expensetracker-999c9',
    authDomain: 'expensetracker-999c9.firebaseapp.com',
    storageBucket: 'expensetracker-999c9.firebasestorage.app',
  );
}
